require 'faraday'
require 'faraday_middleware'
require 'hashie'
require 'faraday_middleware/response_middleware'

require_relative 'coinmarketcap/version'
require_relative 'coinmarketcap/cloud'
require_relative 'coinmarketcap/errors'
require_relative 'coinmarketcap/resources'
require_relative 'coinmarketcap/api'
